import {chartSVG,bars,price} from './market-example.js?v=20260930-release2';

// Zoom out only as the paper plan enters; all labels share the chart's price scale.
export function heroChartState(expansion=0){
 const t=Math.max(0,Math.min(1,expansion));
 const high=1.0896+(1.0936-1.0896)*t,low=1.0862+(1.085-1.0862)*t;
 const top=p=>(28+(high-p)/(high-low)*336)/4;
 return {high,low,target:top(1.0924),entry:top(1.0884),stop:top(1.0864)};
}
export function heroChartHTML(expansion=0){return chartSVG({...heroChartState(expansion),visibleBars:44})}
export function terminalHTML(){return `<div class="terminal-surface">
 <div class="terminal-top"><b><i class="terminal-mark">P</i> PROTrader</b><span>Workspace / EUR/USD</span><small>ACADEMY EXAMPLE</small></div>
 <div class="terminal-workspace"><aside class="terminal-watch"><div class="terminal-heading">WATCHLIST <span>5</span></div><small>FOREX / MAJORS</small>${[['EUR/USD','1.08840','+0.18%'],['GBP/USD','1.26482','+0.12%'],['USD/JPY','149.672','−0.24%'],['AUD/USD','0.65183','+0.08%'],['USD/CHF','0.88461','−0.11%']].map(([s,p,d],i)=>`<div class="watch-row ${!i?'current':''}"><b>${s}</b><span>${p}</span><small class="${d.startsWith('+')?'positive':'negative'}">${d}</small></div>`).join('')}<div class="watch-bottom">SAMPLE SNAPSHOT<br>Prices are illustrative.</div></aside>
 <div class="terminal-main"><div class="terminal-quote"><div><b>EUR/USD</b><span>Euro / US Dollar</span></div><strong>1.08840</strong><small class="positive">+0.18%</small></div><div class="terminal-toolbar"><span>1m</span><span>5m</span><b>15m</b><span>1h</span><span>4h</span><span>1D</span><i></i><span>Indicators</span><span>Drawing tools</span></div><div class="terminal-plot"><div class="chart-ohlc">O ${price(bars.at(-1).open)} <span>H ${price(bars.at(-1).high)}</span><span>L ${price(bars.at(-1).low)}</span><b>C ${price(bars.at(-1).close)}</b></div><div class="terminal-chart-view">${heroChartHTML()}</div><div class="terminal-plan"><div class="terminal-profit-fill"></div><div class="terminal-loss-fill"></div><div class="terminal-level terminal-tp"><b>TP <span>+$188.64</span></b><small>1.09240</small></div><div class="terminal-level terminal-entry"><b>BUY <span>0.48 lot</span></b><small>1.08840</small></div><div class="terminal-level terminal-sl"><b>SL <span>−$99.36</span></b><small>1.08640</small></div></div></div><div class="terminal-dock"><div class="terminal-dock-tabs"><b>Paper plan</b><span>Orders</span><span>Journal</span><small>USD ACCOUNT</small></div><div class="terminal-position"><span><b>EUR/USD</b><small>LONG · LIMIT PLAN</small></span><span><small>Quantity</small>0.48 lot</span><span><small>Entry</small>1.08840</span><span><small>At stop · est.</small><b class="negative">−$99.36</b></span><span><small>At target · est.</small><b class="positive">+$188.64</b></span></div></div></div>
 <aside class="terminal-analysis">
  <section class="terminal-aria"><div class="terminal-heading">ARIA <span>15m · EUR/USD</span></div><div class="terminal-verdict"><b>Review the evidence</b><span>8 of 10 conditions matched</span></div><div class="terminal-checks">${[['Trend & structure','3 / 3',true],['Momentum','3 / 3',true],['Range & close','2 / 2',true],['Pattern & Fib','0 / 2',false]].map(([k,v,ok])=>`<div class="terminal-check"><span>${k}</span><b class="${ok?'positive':'neutral'}">${v}</b></div>`).join('')}</div><div class="terminal-agreement-strip" aria-hidden="true">${Array.from({length:10},(_,i)=>`<i class="${i<8?'matched':''}"></i>`).join('')}</div><small class="terminal-aria-note">Context first. Confirmation next.</small></section>
  <section class="terminal-oracle"><div class="terminal-heading">ORACLE <span>Agreement</span></div><div class="terminal-oracle-body"><div class="terminal-allocation"><svg viewBox="0 0 100 100" aria-hidden="true"><circle class="terminal-ring-track" cx="50" cy="50" r="42"/><circle class="terminal-ring-value" cx="50" cy="50" r="42" pathLength="100" stroke-dasharray="80 20"/></svg><b>80<span>%</span></b></div><div class="terminal-oracle-key"><b>8 / 10</b><span>Matched checks</span><small>Agreement, not<br>win probability.</small></div></div></section>
  <section class="terminal-sentinel"><div class="terminal-heading">SENTINEL <span>24/7 monitor</span></div><div class="terminal-scan-head"><span>MARKET</span><span>15m</span><span>1h</span><span>4h</span></div>${[['EUR/USD','review','aligned','aligned'],['GBP/USD','mixed','review','aligned'],['USD/JPY','mixed','mixed','direction'],['BTC/USD','pending','review','aligned']].map(([market,...states])=>`<div class="terminal-scan-row"><b>${market}</b>${states.map(state=>`<i class="scan-${state}">${state==='aligned'?'✓':state==='pending'?'·':state==='direction'?'↓':'—'}</i>`).join('')}</div>`).join('')}<small>Closed-candle context · Example</small></section>
 </aside></div>
 <div class="terminal-review"><span class="terminal-heading">JOURNAL / PAPER REVIEW</span><b>Record the reason before the result.</b><div><span>CONTEXT<small>4h trend · 15m structure</small></span><span>RISK PLAN<small>1.0% budget · defined stop</small></span><span>REFLECTION<small>What changed after entry?</small></span></div></div>
 <div class="terminal-status"><span>Illustrative workspace · No live market feed</span><span>EMA 20 / 50 · Volume</span><span>UTC</span></div></div>`}
