/* Original product presentation. All examples are illustrative, never live signals. */
(()=>{
'use strict';
const one=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const guide=id=>document.dispatchEvent(new CustomEvent('academy:guide',{detail:id}));
const film=id=>document.dispatchEvent(new CustomEvent('academy:watch-lesson',{detail:id}));
const tool=key=>document.dispatchEvent(new CustomEvent('academy:tool-guide',{detail:key}));
const arrow='<span aria-hidden="true">↗</span>';
const hero=one('.hero');
hero.innerHTML=`<div class="hero-copy"><div class="eyebrow"><i></i> PROTRADER WORKSPACE + ACADEMY</div><h1>See the setup.<br><em>Understand the decision.</em></h1><p>A clearer view of the market. A stronger reason for your next move. Bring ARIA’s reasoning, Oracle’s agreement and Sentinel’s monitoring into one deliberate process.</p><div class="hero-actions"><a class="dark-button" href="#intelligence">Explore the intelligence ${arrow}</a><button class="outline-button" id="tour"><span aria-hidden="true">▷</span> Watch the overview <small>0:49</small></button></div><div class="hero-facts"><span>Understand the evidence</span><span>Define your risk</span><span>Practise with purpose</span></div></div><div class="hero-visual" id="workspace"><div class="workspace-chrome"><span><i></i> PROTRADER / WORKSPACE</span><span class="example-tag">RECORDED VIEW</span></div><div class="workspace-picture"><img src="/landing-assets/workspace-chart.png" width="1120" height="686" alt="PROTrader’s own chart workspace with candles, indicators and pattern annotations"><div class="workspace-overlay"><span class="eyebrow">THE INTELLIGENCE LAYER</span><h2>More context.<br>Less guesswork.</h2><p>Explore how each layer supports your review.</p><div class="hero-tool-links"><a href="#intelligence" data-select-tool="aria">ARIA ${arrow}</a><a href="#intelligence" data-select-tool="oracle">Oracle ${arrow}</a><a href="#intelligence" data-select-tool="sentinel">Sentinel ${arrow}</a></div></div></div><div class="workspace-caption"><span>YOUR CHART. YOUR REASONING. YOUR DECISION.</span><button id="visual-tour">Take a closer look ${arrow}</button></div></div>`;
one('#tour').onclick=()=>film(8);one('#visual-tour').onclick=()=>{openModal('Inside your workspace.','<img class="workspace-expanded" src="/landing-assets/workspace-chart.png" alt="Recorded PROTrader chart with indicator lines and pattern annotations"><p>A real PROTrader chart view. Prices and annotations are a recorded example, not current market data. Explore the interactive intelligence examples below to understand the role of each system.</p><a class="dark-button" href="https://app.protraderacademy.company/">Open the workspace ↗</a>','PROTRADER / CHART WORKSPACE')};
const tools={
 aria:{eyebrow:'01 / UNDERSTAND',title:'A verdict is only useful<br>when you can explain it.',copy:'ARIA makes the reasoning visible. Inspect ten defined conditions, see what agrees, and give the missing evidence the attention it deserves.',bullets:['Ten inspectable market conditions','Passed and failed checks together','Context before a decision'],cta:'Read the ARIA guide'},
 oracle:{eyebrow:'02 / PUT IT IN CONTEXT',title:'Read the agreement.<br>Keep the uncertainty.',copy:'Oracle brings the same checks into one clear score. Use it to summarise the evidence, then return to the conditions behind the number.',bullets:['A readable view of shared checks','Eight of ten means 80% agreement','A score, not a win probability'],cta:'Read the Oracle guide'},
 sentinel:{eyebrow:'03 / MONITOR & REVIEW',title:'A wider watch.<br>A longer perspective.',copy:'Sentinel monitors configured markets and timeframes around the clock, even when your browser is closed. Review closed-candle context and follow paper setups through their outcomes.',bullets:['Multiple markets and timeframes, 24/7','Closed four-hour trend alignment','Paper outcomes tracked by model version'],cta:'Read the Sentinel guide'}
};
const intel=one('#intelligence');
intel.innerHTML=`<div class="section-heading intelligence-heading"><div><span class="eyebrow">THREE ROLES. ONE CONNECTED PROCESS.</span><h2>Meet the intelligence<br><em>behind your workspace.</em></h2></div><p>From one condition to the wider market.<br>Explore the layers. Understand the difference.</p></div><div class="intelligence-tabs" role="tablist" aria-label="Intelligence systems">${['aria','oracle','sentinel'].map((k,i)=>`<button role="tab" id="tab-${k}" aria-controls="intelligence-panel" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}" data-intel="${k}"><span>0${i+1}</span><b>${k==='aria'?'ARIA':k[0].toUpperCase()+k.slice(1)}</b><small>${['Explain','Summarise','Monitor'][i]}</small></button>`).join('')}</div><div class="intelligence-experience" id="intelligence-panel" role="tabpanel" aria-labelledby="tab-aria" tabindex="0"><div class="experience-copy" id="experience-copy"></div><div class="experience-demo" id="experience-demo"></div></div><div class="intelligence-footer"><p>ARIA explains. Oracle summarises. Sentinel monitors and records.<br><b>You review the evidence and decide.</b></p><button class="text-button" id="tools-together">See the connected workflow ${arrow}</button></div>`;
let selectedTool='aria',scenario=6,market='EUR/USD',timeframe='15m';
const conditions=['EMA stack','RSI momentum','MACD direction','Market structure','Current candle','ATR range','Macro alignment','Stochastic','Recent pattern','Fibonacci zone'];
const scenarioControl=()=>`<div class="scenario-control" role="group" aria-label="Example condition agreement"><button data-scenario="6" aria-pressed="${scenario===6}">6 matched</button><button data-scenario="8" aria-pressed="${scenario===8}">8 matched</button></div>`;
function renderTool(key,focus=false){selectedTool=key;const t=tools[key];all('[data-intel]').forEach(b=>{const on=b.dataset.intel===key;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});one('#intelligence-panel').setAttribute('aria-labelledby','tab-'+key);one('#experience-copy').innerHTML=`<span class="eyebrow">${t.eyebrow}</span><h3>${t.title}</h3><p>${t.copy}</p><ul>${t.bullets.map(x=>`<li>${x}</li>`).join('')}</ul><button class="dark-button" id="read-tool">${t.cta} ${arrow}</button>`;
 const header=`<div class="demo-top"><b>${key==='aria'?'ARIA':key==='oracle'?'Oracle':'Sentinel'}</b><span class="example-tag">INTERACTIVE EXAMPLE</span></div>`;
 if(key==='aria')one('#experience-demo').innerHTML=header+`<div class="demo-context">EUR/USD <span>15m · Example read</span></div>${scenarioControl()}<div class="read-heading"><strong>${scenario}<small>/10</small></strong><span>conditions matched<br><b>${scenario===6?'Waiting for evidence':'Review the remaining conditions'}</b></span></div><div class="condition-grid">${conditions.map((c,i)=>`<div class="condition ${i<scenario?'matched':'unmatched'}"><span aria-hidden="true">${i<scenario?'✓':'—'}</span>${c}<small>${i<scenario?'Matched':'Unmet'}</small></div>`).join('')}</div><p class="demo-note" role="status">${10-scenario} conditions remain unmet. A matching check is evidence, not certainty.</p>`;
 if(key==='oracle')one('#experience-demo').innerHTML=header+scenarioControl()+`<div class="oracle-orbit" style="--agreement:${scenario*10}%"><div><strong>${scenario*10}<small>%</small></strong><span>CONDITION AGREEMENT</span></div></div><div class="agreement-count"><b>${scenario} of 10</b><span>The same checks ARIA explains.</span></div><p class="demo-note" role="status">${scenario*10}% describes matched conditions. It does not predict the chance of a profitable trade.</p>`;
 if(key==='sentinel')one('#experience-demo').innerHTML=header+`<div class="sentinel-summary"><span class="scan-mark" aria-hidden="true">◎</span><div><b>One watch. Many perspectives.</b><p>Example market × timeframe review</p></div></div><div class="market-pills" role="group" aria-label="Example market">${['EUR/USD','GBP/USD','BTC/USD'].map(m=>`<button data-market="${m}" aria-pressed="${m===market}">${m}</button>`).join('')}</div><div class="timeframe-pills" role="group" aria-label="Example timeframe">${['15m','1h','4h'].map(t=>`<button data-timeframe="${t}" aria-pressed="${t===timeframe}">${t}</button>`).join('')}</div><div class="sentinel-read" aria-live="polite"><p class="scan-explanation">${timeframe==='15m'?'A 15-minute read adds entry context beneath the closed 4h trend.':timeframe==='1h'?'An hourly read balances local structure with the closed 4h trend.':'A four-hour read reviews the broader structure at its own candle close.'} ${market==='BTC/USD'?'Crypto trades through weekends; feed gaps can still delay a read.':'Forex trading hours include a weekend pause; 24/7 monitoring does not create new candles while the market is closed.'}</p><div><span>Selected review</span><b>${market} · ${timeframe}</b></div><div><span>Source</span><b>Closed candles</b></div><div><span>Higher-timeframe reference</span><b>Closed 4h trend</b></div><div><span>Outcome tracking</span><b>Paper setup · model version</b></div></div><p class="demo-note">Illustrates the workflow, not a live scan. Markets have different trading hours; updates depend on available data. No broker orders are placed.</p>`;
 one('#read-tool').onclick=()=>tool(key);
 all('[data-scenario]').forEach(b=>b.onclick=()=>{scenario=+b.dataset.scenario;renderTool(key);one(`[data-scenario="${scenario}"]`).focus()});
 all('[data-market]').forEach(b=>b.onclick=()=>{market=b.dataset.market;renderTool(key);one(`[data-market="${market}"]`).focus()});
 all('[data-timeframe]').forEach(b=>b.onclick=()=>{timeframe=b.dataset.timeframe;renderTool(key);one(`[data-timeframe="${timeframe}"]`).focus()});
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&!document.documentElement.classList.contains('motion-paused'))one('#experience-demo').animate([{opacity:.65,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'ease-out'});
 if(focus)one('#tab-'+key).focus();
}
function selectTool(key,focus=false){renderTool(key,focus);if(innerWidth<=850)one('#intelligence-panel').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.classList.contains('motion-paused')?'instant':'smooth'})}
all('[data-intel]').forEach((b,i)=>{b.onclick=()=>selectTool(b.dataset.intel);b.onkeydown=e=>{const keys=['aria','oracle','sentinel'];let n=i;if(e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowLeft')n=(i+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();selectTool(keys[n],true)}});
all('[data-select-tool]').forEach(a=>a.addEventListener('click',()=>renderTool(a.dataset.selectTool)));
renderTool('aria');
one('#tools-together').onclick=()=>openModal('Three roles. One review process.','<ol><li><b>ARIA explains.</b> Read the conditions and identify what is missing.</li><li><b>Oracle summarises.</b> Understand the shared score without counting it as independent confirmation.</li><li><b>Sentinel monitors.</b> Review markets, higher-timeframe context and forward paper outcomes.</li><li><b>You decide.</b> Define your entry, protection, position size and risk before acting.</li></ol><p>These systems structure your review. They do not guarantee an outcome.</p><a class="dark-button" href="https://app.protraderacademy.company/">Explore the workspace ↗</a>','THE CONNECTED WORKSPACE');
const risk=document.createElement('section');risk.id='risk';risk.className='risk-section';risk.innerHTML=`<div class="risk-story"><span class="eyebrow">CONTEXT IS ONLY HALF THE PROCESS</span><h2>Make the downside<br><em>part of the plan.</em></h2><p>Move the stop distance. Watch position size respond. A clearer trade starts with knowing what you are prepared to risk.</p><button class="outline-button" id="risk-guide">Understand risk & position size ${arrow}</button><p class="fine-print">Educational EUR/USD example · USD account<br>Assumes $10 per pip per standard lot. Size rounds down to 0.01 lots. Excludes fees, slippage and execution limits.</p></div><div class="risk-playground"><div class="demo-top"><b>Position planner</b><span class="example-tag">TRY THE EXAMPLE</span></div><div class="risk-inputs"><label for="risk-budget">Risk budget <output id="budget-label" for="risk-budget">$100</output></label><input id="risk-budget" type="range" min="25" max="250" step="25" value="100"><label for="stop-distance">Stop distance <output id="stop-label" for="stop-distance">20 pips</output></label><input id="stop-distance" type="range" min="5" max="50" step="1" value="20"></div><div class="risk-levels" aria-hidden="true"><div class="risk-target"><span>Target · illustrative 2R</span><b id="risk-reward">+$200</b></div><div class="risk-entry"><span>ENTRY</span><span>EUR/USD</span></div><div class="risk-stop"><span>Stop · planned price risk</span><b id="risk-loss">−$100</b></div></div><div class="risk-result" aria-live="polite" aria-atomic="true"><span>Calculated position size</span><strong id="risk-size">0.50 <small>lots</small></strong></div><div class="risk-bottom"><span>No order is placed.</span><button id="reset-risk">Reset example</button></div></div>`;
one('#path').before(risk);
function updateRisk(){const budget=+one('#risk-budget').value,stop=+one('#stop-distance').value,size=Math.floor((budget/(stop*10)+1e-9)*100)/100,loss=size*stop*10;one('#budget-label').textContent='$'+budget;one('#stop-label').textContent=stop+' pips';one('#risk-reward').textContent='+$'+(loss*2).toFixed(2);one('#risk-loss').textContent='−$'+loss.toFixed(2);one('#risk-size').innerHTML=size.toFixed(2)+' <small>lots</small>';one('.risk-stop').style.minHeight=(44+stop)+'px'}
one('#risk-budget').oninput=updateRisk;one('#stop-distance').oninput=updateRisk;one('#reset-risk').onclick=()=>{one('#risk-budget').value=100;one('#stop-distance').value=20;updateRisk()};one('#risk-guide').onclick=()=>guide(0);
one('#path').innerHTML=`<div class="path-heading"><span class="eyebrow">THE ACADEMY MAKES IT PRACTICAL</span><h2>Build understanding.<br><em>Then build your process.</em></h2><p>The workspace gives you tools. The Academy helps you use them with intention.</p><a class="text-button" href="/classroom#start">New here? Start the guided introduction ↗</a></div><div class="learning-steps"><article><span>01 / LEARN</span><h3>Understand one thing well.</h3><p>Start with a clear written explanation. Watch a short Callan-narrated lesson when you want a demonstration.</p><button data-guide-shortcut="1">Start with chart essentials ${arrow}</button></article><article><span>02 / PRACTISE</span><h3>Put the idea on a chart.</h3><p>Define entry, stop and size in a paper workspace. Check the relationship between your plan and your risk.</p><button data-guide-shortcut="0">Prepare a trade plan ${arrow}</button></article><article><span>03 / REVIEW</span><h3>Keep the reasoning.</h3><p>Record the decision as well as the result. Bring better questions to your next lesson or instructor session.</p><button data-guide-shortcut="3">Make a practice note ${arrow}</button></article></div>`;
all('[data-guide-shortcut]').forEach(b=>b.onclick=()=>guide(+b.dataset.guideShortcut));
one('#learn .eyebrow').textContent='YOUR LEARNING LIBRARY';one('#learn h2').textContent='Read it. See it. Try it.';
const libraryButton=one('#library-toggle');const refreshLibrary=()=>{const open=libraryButton.getAttribute('aria-expanded')==='true';libraryButton.innerHTML=(open?'Close the library':'Explore 10 guides & videos')+' <span aria-hidden="true">'+(open?'−':'+')+'</span>'};libraryButton.addEventListener('click',refreshLibrary);refreshLibrary();
one('.library-context').textContent='Written guides first. Optional videos, captions and chapter navigation when you want to see the tools in action.';
all('[data-video-filter]').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('selected')));b.addEventListener('click',()=>all('[data-video-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b))))});
const faq=document.createElement('section');faq.className='faq-section';faq.id='questions';faq.innerHTML=`<div><span class="eyebrow">A FEW THINGS WORTH KNOWING</span><h2>Clarity starts here.</h2><button class="text-button" id="faq-alex">Ask Alex a question ${arrow}</button></div><div class="faq-list">${[
 ['Is Oracle a prediction of winning?','No. Oracle summarises the same defined conditions that ARIA explains. Eight matched conditions out of ten means 80% agreement, not an 80% chance of profit.'],
 ['Does Sentinel work when I close the browser?','Yes. Sentinel runs on the server across configured markets and timeframes. It reviews closed candles and tracks paper setups by model version. Market hours and data availability affect updates; it does not place broker orders.'],
 ['Where should I start?','Open a written chart or risk guide, watch the optional demonstration, then practise in the paper workspace. The Academy and the trading app have separate sign-ins.'],
 ['Can I ask for help?','Ask Alex by text or choose Call Alex for voice support. For account or class questions, use the Academy team contact page. Alex does not see your private account, positions or journal.']
].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`;one('.closing').before(faq);one('#faq-alex').onclick=()=>openAlexSupport('text');
one('.closing').innerHTML=`<div><span class="eyebrow">YOUR NEXT STEP. CLEARER.</span><h2>More understanding.<br><em>More intention.</em></h2><p>Explore the tools. Learn their limits.<br>Make your process your own.</p></div><div class="closing-actions"><a class="dark-button" href="https://app.protraderacademy.company/">Open PROTrader ${arrow}</a><a class="outline-button" href="#learn">Explore the Academy ${arrow}</a><span>Educational tools. No guaranteed outcomes.</span></div>`;
// Real links preserve browser navigation and open-in-new-tab behavior.
const nav=one('.site-header nav');nav.id='site-navigation';nav.setAttribute('aria-label','Main navigation');nav.innerHTML='<a href="#intelligence">Intelligence</a><a href="#risk">Risk & process</a><a href="#learn">Academy</a><a href="/classroom#classroom">My classroom</a>';
const menu=document.createElement('button');menu.className='menu-toggle';menu.id='menu-toggle';menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-controls','site-navigation');menu.innerHTML='Menu <span aria-hidden="true">☰</span>';one('.site-header').append(menu);
function closeMenu(){menu.setAttribute('aria-expanded','false');one('.site-header').classList.remove('menu-open')}
menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));one('.site-header').classList.toggle('menu-open',open)};
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus()}});document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu()});
// Motion adds orientation, never blocks content or competes with reading.
const motionButton=document.createElement('button');motionButton.className='motion-toggle';motionButton.textContent='Pause motion';motionButton.setAttribute('aria-pressed','false');one('footer').append(motionButton);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;function setMotion(value){paused=value;document.documentElement.classList.toggle('motion-paused',paused);motionButton.disabled=reduced.matches;motionButton.textContent=reduced.matches?'Reduced motion enabled':paused?'Enable motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(paused))}setMotion(paused);motionButton.onclick=()=>setMotion(!paused);reduced.addEventListener('change',e=>setMotion(e.matches));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});all('.intelligence,.risk-section,.path,.library,.faq-section,.closing').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
// Header section state is tied to the visible content, not only the last click.
if('IntersectionObserver' in window){const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)nav.querySelectorAll('a').forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}),{rootMargin:'-15% 0px -60% 0px'});['intelligence','risk','learn'].forEach(id=>navObserver.observe(one('#'+id)))}
})();
