export const videos = ["https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/bf139c70-aec0-4497-bbf4-6d3f3acfc0ce.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/1d98cd13-fc8a-47fd-9df8-521eb5840f09.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/4fc060d6-47d6-4722-a54d-91a056bc659e.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/3c419c0f-63e9-4e9f-95a0-be3f51842d4d.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/d1d5e502-ee4d-4d19-a45f-8b032eb2480f.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/98476413-cca1-4ab9-8744-be26f9d6df47.mp4","https://d2ol7oe51mr4n9.cloudfront.net/user_3JK9HzQtMubHcINDjvbZuTRS9eo/a3748e4a-9ed5-4596-a7ef-5a86664bd7e4.mp4"].map((url,i)=>({url,id:i,duration:'0:30',...[
{title:'Know your trade ticket',topic:'Trade & risk',label:'01 / TRADE TICKET',summary:'Find direction, order type, lot size, stop loss and take profit. Review Max Loss, margin and risk-to-reward estimates before a paper order.',steps:['Open Trade and select Buy or Sell.','Choose the order type and lot size; enable stop loss and take profit.','Change the lot size and describe how the loss estimate changes.'],note:'Estimates depend on your inputs and instrument. Review every field before submitting.'},
{title:'Make your chart readable',topic:'Chart foundations',label:'02 / CHART TOOLS',summary:'Select a market and timeframe, then use H-Line, Trend and Fib to annotate a prepared chart.',steps:['Choose your market and timeframe.','Use H-Line for a level or Trend to connect two points.','Return to Cursor and remove drawings that do not help explain your observation.'],note:'A marked level describes an observation; it does not guarantee a price reaction.'},
{title:'Read a pattern with context',topic:'Analysis tools',label:'03 / SCANNER',summary:'Review the pattern name, direction and score in Scanner, then compare available overlays with the chart.',steps:['Open Scanner for the selected market and timeframe.','Read one pattern’s name, direction and score.','Toggle Patterns and compare the overlay with price action.'],note:'A scanner score is a review cue, not a guaranteed outcome.'},
{title:'Turn a close into a review',topic:'Practice & review',label:'04 / JOURNAL',summary:'After a paper position closes, read its direction, closed volume, instrument and profit or loss together in Journal.',steps:['Close a paper position in your practice environment.','Open Journal beneath the chart; read the latest entry.','Explain the result and note one thing to review next time.'],note:'Partial closes can create separate entries. Profit or loss alone does not explain a decision.'},
{title:'Find your flow with shortcuts',topic:'Chart foundations',label:'05 / SHORTCUTS',summary:'Open the shortcut reference and learn two keys you can use during each session.',steps:['Press ? to open Keyboard Shortcuts.','Use 1–6 for timeframes; A for ARIA, O for Oracle, P for Portfolio.','Press Escape to close help, then practice two shortcuts.'],note:'Use shortcuts while focus is outside a text input.'},
{title:'Understand ARIA’s checks',topic:'Analysis tools',label:'06 / ARIA',summary:'Read market conditions, nine gates and the verdict. Review what applying ARIA copies into the Trade ticket.',steps:['Open ARIA and read market conditions and the nine gates.','Explain the verdict and any restrictions.','When available, Apply ARIA to Trade copies direction, stop and target; check the paper ticket.'],note:'Gates count matching conditions, not your chance of winning.'},
{title:'What Oracle’s percentage means',topic:'Analysis tools',label:'07 / ORACLE',summary:'Understand the percentage as the share of nine ARIA checks that pass, then read the reasons and suggested trade.',steps:['Open Oracle and read the reasons behind its percentage.','Compare the same setup with ARIA’s verdict and restrictions.','If applying the signal, check size manually: suggested size is not copied.'],note:'78% means seven of nine checks passed. It is not a predicted win rate. This clip is caption-only.'}
][i]}));
export const lessons = [
{title:'Get oriented',summary:'Meet the academy, understand paper trading and find your way around Pro Trader.',concept:'Paper trading is simulated practice. Begin by identifying the selected market and timeframe, then locate the chart, Trade panel and Journal. Keep account mode visible throughout your practice.',exercise:'Locate the chart, market selector, timeframe selector, Trade panel and Journal. Write one sentence explaining each.',deeper:'Map your current workflow to these tools. Identify a step you tend to skip.',check:'How will you confirm you are practicing without placing a live trade?',video:4},
{title:'Read and annotate a chart',summary:'Understand candles and timeframes, and mark a clear observation.',concept:'Each candle summarizes a time interval. A different timeframe changes the view. Use a prepared chart to describe what happened before drawing conclusions about what might happen next.',exercise:'On a prepared chart, mark one horizontal level and describe the observation behind it.',deeper:'Compare two timeframes. Explain what is visible in one view but less clear in the other.',check:'What does your marked level tell you, and what does it not tell you?',video:1},
{title:'Understand the practice ticket',summary:'Learn the fields and explain an order before any paper submission.',concept:'Direction, order type, size, stop loss and take profit describe different parts of a ticket. Displayed estimates depend on these inputs. Review the complete ticket and explain it in your own words.',exercise:'Identify each field on a prepared paper ticket. Explain the direction, size, stop and target without submitting a live order.',deeper:'Compare two prepared tickets that differ only in size. Explain the change in displayed loss estimate.',check:'Which fields would you review if the loss estimate looked unexpected?',video:0},
{title:'Interpret app analysis',summary:'Read Scanner, ARIA and Oracle as information to examine.',concept:'Scanner surfaces detected patterns. ARIA checks conditions and displays a verdict. Oracle’s percentage reflects the proportion of nine checks passed. These outputs are not predicted win rates.',exercise:'Describe one Scanner output and one ARIA verdict. List a question the output does not answer.',deeper:'Compare the output with the chart and check whether ARIA restrictions still apply.',check:'What does seven of nine checks passing mean? Why is it not a win probability?',video:5},
{title:'Complete a practice workflow',summary:'Connect observation, a written plan, paper ticket review and reflection.',concept:'A repeatable process connects what you observe with why you act and what you review. Write your practice plan first. Review the paper ticket, then use Journal after a paper close to understand what was recorded.',exercise:'Write an observation and practice plan, review a paper ticket, then describe a Journal entry after a paper close.',deeper:'Complete the sequence independently and identify where your actions differed from the plan.',check:'What did your process teach you beyond the recorded profit or loss?',video:3},
{title:'Practice clinic',summary:'Return to unclear steps and work through recurring questions.',concept:'Use this session to make the workflow easier to explain and repeat. Bring one precise question and the step where you got stuck. Work through that step on a prepared paper example.',exercise:'Repeat your least clear step from sessions 1–5 and explain it to another learner.',deeper:'Try the same task on a different prepared chart and describe what changes.',check:'Can you explain the step without relying on a memorized button sequence?',video:2},
{title:'Review and next steps',summary:'Check understanding and choose what needs another practice pass.',concept:'The practical check focuses on understanding, not profitability. Identify the tools, explain a paper ticket, interpret an analysis output and reflect on a Journal entry. Your instructor will confirm the next learning steps.',exercise:'Complete the workflow and record one thing you understand, one uncertainty and one question for your instructor.',deeper:'Explain the limitations of each analysis tool in your workflow.',check:'Which part can you now complete independently, and which needs guidance?',video:6}
];
