const instructorDrafts=new Map();
window.addEventListener('academy-session-changed',()=>instructorDrafts.clear());
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>crypto.randomUUID();
async function api(path,data){const response=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Please try again.');return result}
const time=t=>new Date(t*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function messagesHTML(messages,inbox=false){return messages.map(m=>`<article class="chat-message chat-${m.role}"><small>${esc({visitor:inbox?'Student / visitor':'You',human:'Academy team',assistant:'AI assistant',system:'Support update'}[m.role]||m.role)} · ${time(m.created)}</small><p>${esc(m.body)}</p></article>`).join('')}
export function initSupport(){const root=document.createElement('div');root.id='academy-chat';root.innerHTML=`<button id="chat-launch" aria-expanded="false" aria-controls="chat-window">◌ <span>Need help?</span></button><section id="chat-window" role="dialog" aria-label="Academy support chat" hidden><div class="chat-header"><div><b>Academy support</b><small id="chat-status">Messages and guidance</small></div><button id="chat-close" aria-label="Close support chat">✕</button></div><div class="chat-intro"><p>Ask about the Academy, classes, or your account. Avoid passwords and financial information.</p><label id="chat-ai-choice" hidden><input type="checkbox" id="chat-ai-consent"> Use AI help. My chat messages may be sent to OpenAI. I can choose a human instead.</label><p><a href="#privacy">Privacy policy</a> · Guests: keep this browser to see replies, or sign in to keep conversations with your account.</p></div><div id="chat-messages" role="log" aria-live="polite" aria-relevant="additions"></div><p id="chat-error" role="status"></p><form id="chat-form"><label for="chat-body" class="chat-label">Your message</label><textarea id="chat-body" maxlength="3000" rows="2" required placeholder="How can we help?"></textarea><div class="chat-actions"><button type="button" id="chat-human">Talk to a person</button><button type="submit" id="chat-send">Send</button></div></form></section>`;document.body.append(root);const q=s=>root.querySelector(s);let current=null,busy=false,timer=null,last='',pending=null,sessionVersion=0;
function paint(data){current=data;q('#chat-ai-choice').hidden=!data.aiAvailable;const labels={new:data.aiAvailable?'AI help or a person — your choice':'Human support · Leave a message',ai:'AI assistant · Ask a person any time',assistant_pending:'AI assistant is preparing a reply…',waiting:'Waiting for a human reply',human:'Academy team replied',closed:'Conversation resolved · Send to reopen'};q('#chat-status').textContent=labels[data.status]||'Academy support';const signature=JSON.stringify(data.messages);if(signature!==last){q('#chat-messages').innerHTML=messagesHTML(data.messages);q('#chat-messages').scrollTop=q('#chat-messages').scrollHeight;last=signature}}
async function refresh(){if(q('#chat-window').hidden||busy)return;const version=sessionVersion;try{const data=await api('support');if(version!==sessionVersion)return;paint(data);q('#chat-error').textContent=''}catch(e){q('#chat-error').textContent='Unable to refresh. Your messages will appear when the connection returns.'}}
function close(){q('#chat-window').hidden=true;q('#chat-launch').setAttribute('aria-expanded','false');clearInterval(timer);q('#chat-launch').focus()}
q('#chat-launch').onclick=async()=>{q('#chat-window').hidden=false;q('#chat-launch').setAttribute('aria-expanded','true');await refresh();q('#chat-body').focus();clearInterval(timer);timer=setInterval(refresh,5000)};q('#chat-close').onclick=close;root.addEventListener('keydown',e=>{if(e.key==='Escape')close()});root.querySelector('a[href="#privacy"]').onclick=close;
async function send(human=false){if(busy)return;const body=q('#chat-body').value.trim()||(human?'I would like to speak to a human support agent.':'');if(!body)return;const version=sessionVersion;busy=true;q('#chat-send').disabled=q('#chat-human').disabled=true;q('#chat-error').textContent='Sending…';if(!pending||pending.body!==body||pending.human!==human)pending={body,human,clientId:key(),aiConsent:q('#chat-ai-consent').checked};try{const data=await api('support-message',pending);if(version!==sessionVersion)return;paint(data);q('#chat-body').value='';pending=null;q('#chat-error').textContent=''}catch(e){q('#chat-error').textContent=e.message+' Your draft is still here; retrying will not duplicate a saved message.'}finally{busy=false;q('#chat-send').disabled=q('#chat-human').disabled=false}}
q('#chat-form').onsubmit=e=>{e.preventDefault();send()};q('#chat-human').onclick=()=>send(true);
window.addEventListener('academy-session-changed',()=>{sessionVersion++;current=null;last='';pending=null;q('#chat-messages').replaceChildren();q('#chat-body').value='';q('#chat-ai-consent').checked=false;refresh()});
}
export function supportInbox(){return `<section class="page-heading compact"><p class="eyebrow">HUMAN SUPPORT INBOX</p><h1>Keep the conversation<br><em>in one place.</em></h1><p>Students and guests receive your replies in the website chat. Verified students are also notified by email. No automatic response-time promise is shown.</p></section><section class="support-inbox"><aside class="panel"><button class="button secondary" id="support-refresh">Refresh conversations</button><div id="support-threads"></div></aside><article class="panel" id="support-thread"><p>Select a conversation to read and reply.</p></article></section>`}
export async function bindSupportInbox(){let active=null,timer,replyKey=null;const list=document.querySelector('#support-threads'),pane=document.querySelector('#support-thread');if(!list)return;const showError=e=>{let node=document.querySelector('#support-inbox-error');if(!node){node=document.createElement('p');node.id='support-inbox-error';list.before(node)}node.textContent=e.message};async function loadList(){try{const data=await api('support-admin');list.innerHTML=data.threads.map(t=>`<button class="support-thread-button" data-thread="${t.id}"><b>${esc(t.name||'Guest')} · #${t.id}</b><small>${esc(t.status.replaceAll('_',' '))} · ${new Date(t.updated*1000).toLocaleString()}</small></button>`).join('')||'<p>No support conversations yet.</p>'}catch(e){showError(e)}}
async function loadThread(id){try{const data=await api('support-admin-thread',{thread:id});if(active!==id)return;const old=instructorDrafts.get(id)||'';pane.innerHTML=`<h2>Conversation #${id}</h2><div class="inbox-messages">${messagesHTML(data.messages,true)}</div><form id="support-reply-form"><label for="support-reply">Reply as the Academy team</label><textarea id="support-reply" rows="4" maxlength="3000" required>${esc(old)}</textarea><p id="support-reply-status" role="status"></p><button class="button" type="submit">Send human reply</button><button class="button secondary" type="button" id="support-resolve">Mark resolved</button></form>`;document.querySelector('#support-reply').oninput=e=>instructorDrafts.set(id,e.target.value);document.querySelector('#support-reply-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter,body=document.querySelector('#support-reply').value.trim();if(!body)return;b.disabled=true;if(!replyKey||replyKey.body!==body)replyKey={body,clientId:key()};try{await api('support-admin-reply',{thread:id,...replyKey});document.querySelector('#support-reply').value='';instructorDrafts.delete(id);replyKey=null;await loadThread(id);await loadList()}catch(err){document.querySelector('#support-reply-status').textContent=err.message;b.disabled=false}};document.querySelector('#support-resolve').onclick=async()=>{try{await api('support-admin-close',{thread:id});await loadList();document.querySelector('#support-reply-status').textContent='Conversation marked resolved.'}catch(e){document.querySelector('#support-reply-status').textContent=e.message}}}catch(e){showError(e)}}
list.onclick=e=>{const b=e.target.closest('[data-thread]');if(b){if(active!==+b.dataset.thread){active=+b.dataset.thread;replyKey=null;pane.innerHTML=''}loadThread(active)}};document.querySelector('#support-refresh').onclick=()=>{loadList();if(active)loadThread(active)};await loadList();}
